apiVersion: batch/v1
kind: Job
metadata:
  name: springbox-reviews-job-populate-db
spec:
  template:
    metadata:
      name: springbox-reviews-job-populate-db
      labels:
        app: springbox
        component: reviews
        job: populate-db
    spec:
      restartPolicy: Never
      containers:
      - name: populate-db
        image: everpeace/curl-jq:latest
        command: ["/bin/bash", "-c" ]
        args: 
        - >
          set -x;
          ROUTE=http://springbox-reviews:8080;
          AUTH_ROUTE=http://springbox-auth-server:9999/uaa;
          TOKEN=`curl -X POST -u acme:acmesecret ${AUTH_ROUTE}/oauth/token\?grant_type=password\&username=mstine\&password=secret\&scope=openid | jq -r '.access_token'`;
          until curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 40  -i -H "Authorization: Bearer ${TOKEN}" ${ROUTE}/reviews -X POST -d '{"userName":"mstine","mlId":"1","title":"Toy Story (1995)","review":"Great movie!","rating":"5"}' -H "Content-Type: application/json"; do sleep 1; done;
          until curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 40 -i -H "Authorization: Bearer ${TOKEN}" ${ROUTE}/reviews -X POST -d '{"userName":"mstine","mlId":"2","title":"GoldenEye (1995)","review":"Pretty good...","rating":"3"}' -H "Content-Type: application/json"; do sleep 1; done;
          until curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 40 -i -H "Authorization: Bearer ${TOKEN}" ${ROUTE}/reviews -X POST -d '{"userName":"starbuxman","mlId":"2","title":"GoldenEye (1995)","review":"BOND BOND BOND!","rating":"5"}' -H "Content-Type: application/json"; do sleep 1; done;
          until curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 40 -i -H "Authorization: Bearer ${TOKEN}" ${ROUTE}/reviews -X POST -d '{"userName":"starbuxman","mlId":"4","title":"Get Shorty (1995)","review":"Meh","rating":"3" }}' -H "Content-Type: application/json"; do sleep 1; done;
          until curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 40 -i -H "Authorization: Bearer ${TOKEN}" ${ROUTE}/reviews -X POST -d '{"userName":"starbuxman","mlId":"5","title":"Copycat (1995)","review":"Nicely done!","rating":"4"}' -H "Content-Type: application/json"; do sleep 1; done;
          until curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 40 -i -H "Authorization: Bearer ${TOKEN}"  ${ROUTE}/reviews -X POST -d '{"userName":"littleidea","mlId":"2","title":"GoldenEye (1995)","review":"Good show!","rating":"4"}' -H "Content-Type: application/json"; do sleep 1; done;
          until curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 40 -i -H "Authorization: Bearer ${TOKEN}"  ${ROUTE}/reviews -X POST -d '{"userName":"littleidea","mlId":"3","title":"Four Rooms (1995)","review":"Could have been better...","rating":"3"}' -H "Content-Type: application/json"; do sleep 1; done;
          until curl --connect-timeout 5 --max-time 10 --retry 5 --retry-delay 1 --retry-max-time 40 -i -H "Authorization: Bearer ${TOKEN}"  ${ROUTE}/reviews -X POST -d '{"userName":"littleidea","mlId":"5","title":"Copycat (1995)","review":"Nicely done!","rating":"4"}' -H "Content-Type: application/json"; do sleep 1; done;
