apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbox
    component: reviews
  name: springbox-reviews
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springbox
    component: reviews
  type: ClusterIP


