apiVersion: v1
kind: ConfigMap
metadata:
  name: springbox-reviews
  labels:
    app: springbox
    component: reviews
data:
  application.yaml: |+
    spring:
      data:
        mongodb:
          uri: mongodb://mongodb-mongodb:27017/reviews
  bootstrap.yaml: |+
    spring:
      application:
        name: springbox-reviews
      cloud:
        config:
          uri: http://springbox-config-server:8888
