server:
  port: 9000

zuul:
  routes:
    springbox-catalog: /catalog/**
    springbox-reviews: /reviews/**
    springbox-recommendations: /recommendations/**
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user

security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user


logging:
  level:
    org.springframework.security: DEBUG 
    org.springframework.cloud.netflix: INFO
    com.netflix.zuul: INFO
    io.springbox.apigateway: DEBUG
