apiVersion: v1
kind: ConfigMap
metadata:
  name: springbox-eureka
  labels:
    app: springbox
    component: eureka
data:
  application.yaml: |+
    server:
      port: 8761
    
    eureka:
      instance:
        hostname: springbox-eureka
      client:
        registerWithEureka: false
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
