apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbox
    component: catalog
  name: springbox-catalog
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springbox
    component: catalog
  type: ClusterIP


