apiVersion: v1
kind: ConfigMap
metadata:
  name: springbox-catalog
  labels:
    app: springbox
    component: catalog
data:
  application.yaml: |+
    spring:
      jpa:
        hibernate:
          ddl-auto: create-drop
   
    ---
    
    spring:
      profiles: default
      jpa:
        database: HSQL
   
    ---
    
    spring:
      profiles: cloud
      jpa:
        database: POSTGRESQL

  bootstrap.yaml: |+
    spring:
      application:
        name: springbox-catalog
      cloud:
        config:
          uri: http://springbox-config-server:8888
