apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springbox-api-gateway
spec:
  tls:
  - hosts:
    - jkwong-kube-422189.us-south.containers.mybluemix.net
    secretName: jkwong-kube-422189
  rules:
  - host: jkwong-kube-422189.us-south.containers.mybluemix.net
    http:
      paths:
      - path: /
        backend:
          serviceName: springbox-api-gateway
          servicePort: 8080
      - path: /uaa
        backend:
          serviceName: springbox-auth-server
          servicePort: 9999
