apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: springbox-auth-server
spec:
  rules:
  - host: jkwong-kube-422189.us-south.containers.mybluemix.net
    http:
      paths:
      - path: /uaa
        backend:
          serviceName: springbox-auth-server
          servicePort: 9999
