apiVersion: v1
kind: ConfigMap
metadata:
  name: springbox-recommendations
  labels:
    app: springbox
    component: recommendations
data:
  application.yaml: |+
    logging:
      logging:
        org.springframework.web: DEBUG
        io.springbox.recommendations: DEBUG
    
    spring:
      data:
        neo4j:
          driver: org.neo4j.ogm.drivers.http.driver.HttpDriver 
          uri: http://neo4j-neo4j:7474
          username: neo4j
          password: secret
  bootstrap.yaml: |+
    spring:
      application:
        name: springbox-recommendations
      cloud:
        config:
          uri: http://springbox-config-server:8888
