kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    app: springbox
    component: recommendations
  name: springbox-recommendations
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springbox
      component: recommendations
  template:
    metadata:
      labels:
        app: springbox
        component: recommendations
    spec:
      containers:
      - image: jkwong/springbox-recommendations:latest
        imagePullPolicy: Always
        name: springbox-recommendations
        ports:
        - containerPort: 8082
          name: http 
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: springbox-recommendations-config
