apiVersion: v1
kind: Service
metadata:
  labels:
    app: springbox
    component: config-server
  name: springbox-config-server
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: springbox
    component: config-server
  type: ClusterIP


