apiVersion: v1
kind: ConfigMap
metadata:
  name: springbox-config-server
  labels:
    app: springbox
    component: config-server
data:
  bootstrap.yaml: |+
    server:
      port: 8888
    application:
      name: springbox-config-server
    encrypt:
      key: ${ENCRYPT_KEY}

  application.yaml: |+
    spring:
      rabbitmq:
        addresses: rabbitmq:5672
      cloud:
        config:
          server:
            git:
              uri: https://github.com/jkwong888/springbox-config-repo


